---
- import_tasks: pre-upgrade.yml

- name: Flannel | Create Flannel manifests
  template:
    src: "{{item.file}}.j2"
    dest: "{{kube_config_dir}}/{{item.file}}"
  with_items:
    - {name: flannel, file: cni-flannel-rbac.yml, type: sa}
    - {name: kube-flannel, file: cni-flannel.yml, type: ds}
  register: flannel_node_manifests
  when:
    - inventory_hostname in groups['kube-master']

- name: Flannel | Create Flannel pods
  template:
    src: "cni-flannel-pod.yml.j2"
    dest: "{{ kube_config_dir }}/cni-flannel-pod.yml"
